FROM node:latest

WORKDIR /app

COPY package.json .

RUN npm config set registry https://registry.npmmirror.com/

RUN npm install

COPY . .

RUN npm run build

EXPOSE 7777

CMD [ "node", "./dist/main.js" ]